hash-format = "sha256"

[[files]]
file = "kubejs/README.txt"
hash = "989f3737ae4621b8ff6730bce4cbeeee756921e7e510e0c281c8a350501d98af"

[[files]]
file = "kubejs/assets/kubejs/textures/item/enderman_card.png"
hash = "e7158121fe826a5536a2bc9539d97b65042968e51e8534e8ac45306f5c8ba922"

[[files]]
file = "kubejs/assets/kubejs/textures/item/lantern_card.png"
hash = "138be4398437a834ea381fc12f4c149ead91d1d7ac37d6a757657a8289042703"

[[files]]
file = "kubejs/assets/kubejs/textures/item/trial_key_card.png"
hash = "6fa6e38143ab9f6daf70f3af7b219b5e08a5bac72e075f18b214fa0f92349d99"

[[files]]
file = "kubejs/client_scripts/jsconfig.json"
hash = "0bbdb4b618f793cd4f63df515fd291e9ec15b7ff8c75744717c7ab468e9b2172"

[[files]]
file = "kubejs/client_scripts/main.js"
hash = "a9b27948dc4ac9c14f2955ddca25fe5ac8298b692b5a6fcb79cbb7bceea03b5c"

[[files]]
file = "kubejs/client_scripts/placement.js"
hash = "efa81ca325c8aea0c0924f7c8014ad08889778c79e38ec64f9bbed80396733b4"

[[files]]
file = "kubejs/client_scripts/tooltips.js"
hash = "7e49f31450aff611a789f00d655f9a3a0d0c63cac7af75471fb485327d789b13"

[[files]]
file = "kubejs/config/client.json"
hash = "f38d326943014d6906916a9387c75e2bfd609fce10e92049d76a395c5775b6f1"

[[files]]
file = "kubejs/config/common.json"
hash = "e00a67922942660d77c213379b5128a46c5abc894178b0be04006d325ff5f6b3"

[[files]]
file = "kubejs/config/probe-settings.json"
hash = "e7f66959876333e6ebb47790be63705a2999729ebf637adf7db7a405949a45ea"

[[files]]
file = "kubejs/config/web_server.json"
hash = "c5bb7789527e27eab525cbfeb658a9419c7c5830fd6c2d6b379b6fbe4df0480a"

[[files]]
file = "kubejs/server_scripts/cards.js"
hash = "f68a2afc9a2ed0bf8ffdb663fe21b71e827cf0edf7d8b45186d489e4f045a496"

[[files]]
file = "kubejs/server_scripts/item_deposit.js"
hash = "09c53947a4f42db68ce0b07d4e9b8c4757c51772c597faf63112e43c5109c8ca"

[[files]]
file = "kubejs/server_scripts/jsconfig.json"
hash = "ecbeb788ddebbc1bbd47e68e16f2c8aed37f0d15d2f692734e21d88937f49228"

[[files]]
file = "kubejs/startup_scripts/item_deposit_functions.js"
hash = "248c14b9dc868a7dc86152d8e83f1f663cd216d4b999340897cfd1006044f3a1"

[[files]]
file = "kubejs/startup_scripts/jsconfig.json"
hash = "5d1d34f9763eb77f2e30b9fb62a8f4f056149b2c162b113157265ddef1b8dad3"

[[files]]
file = "kubejs/startup_scripts/main.js"
hash = "251fafb3e23f31534a424c5bef8c013b16eae2c0e76b82b6e74873f22a943034"

[[files]]
file = "kubejs/startup_scripts/util.js"
hash = "57293e4739c31e5cfc9d0f8e857c8fa16b5ebb54b2d8bace64cab32121946adb"

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "2b02594380f31aa857c89d296afb53bec67621b491956be09a54ab6845552e2a"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "fb413ba504cfaae8ab4d96ede3944b8eb15fa4238ae02b4331bdad2549876f2e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/attributefix.pw.toml"
hash = "f0edb6932d0c3f97338cf660763ff43bc5febdf0eb5edeca3a1927c20f14e296"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "34b9ccfc5e13dc8c89c502495a29d2c0cf66e9b3c5fec3c86262976fe1dff3f9"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
hash = "88908286eebea979713b5626891f634317fcc4c5a5bd4ec0c9444a33863a4518"
metafile = true

[[files]]
file = "mods/cardhunterscore-1.0.0.jar"
hash = "32b9b824264cb3ecd54fb9bd23eaa3e8646c1537a8d7156dd90092ddd9c6d5d9"

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "88773a3eb40bdea95e454e38e9f8b8154d119997fbdd31c7c4bf8c24baaf4de4"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "4d9264c9550ed32948bd6ea78cb53ba80dd01da8e6c10fa8de4fa52c1bff4d8d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/common-network.pw.toml"
hash = "cd8078f4d044e9fb548c2b792f2f1f1c04e1b80e1479446f67de3e8687dfbf67"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "ccd912d3f084b90ae88115cb9b041031aa4da4bb18213b585805fd11b19bdb48"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "f36d13fe08a755712437ae38d4a339af7a73003152a8d3638984a11964fd83ae"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "ec2cfea39ef0e01a94bf83738349e2b927178127bbe248f6edb2ed020eb406f3"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "cd4c4ec6ef26d2b61e0cb0bdd398e8d528b88ebf739fc0898bc8cb2f7a88debb"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "0603752f5a3db14a380597c84cdb80c3b66564a69d8c7f5c4f1d35c4f2a32924"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
hash = "b53c40130b7c2f91237cf62480877414296fbea3525f2c824351c0c07f136ddb"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "95218d2192befc4f1f60adda3e7898f38af351df02f78e1e481b77a8afd6d01c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgematica.pw.toml"
hash = "a8bdefffee0ac7aab23ffd3ffdc2e7ce8a36048828dffdb3ae1911c82d84a1b0"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "939c71e9b7d893e65560ada8a5b7ad0c8f000db400ddbec814e038d2a2cb99c0"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "11c4ac6932c14f3ad5a2c63d7f39eee1e9a2a91ffc079d5bd917c9aa381abdfb"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "960fb33c17aca9c635f99009c1f16d75c312d043e302a599f6ce8040452079e6"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "019fea93516a470bbcad284dd0cbad6f4e2914d96221c86e3f87c12fe6321e10"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6bdf101d3d5ec8729a8095d5853f80eb925a47c889cd10de6704b20cc7f3c73e"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "f67aa60c765593a8c70f78296a460349c6aef5f4a16d173eae02e8803b545ad4"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "9163b758163681f75e2048c798be880c50392684b127d7d87f42ea588deceb62"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "e7d3f7e0472ba9a3ef946fa5defcb157e4126636e603c2306d4ad6065936d5e2"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "076be436a9dd1df44f71473123db01ad52b26afce495615d91ec5150e1960d98"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1a9ec5beaba1be3151b8710db2bfab90c2063a4dafaf2720336852245a145cc4"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "6f1883653a606626e1e32654439c5a2b3a48a385b22290152a624009cd744492"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "3f907a8532b4ca98390055ca0cb1bbd87e8ebcd44be6afe9b69280859ff37035"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "9ca14134538c66b6d8ef74107f6b15ba9487ec632d984427e84ad38aa47afa60"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/loot-beams-refork.pw.toml"
hash = "bd0df74b439b6df68bc0a6466a709b66bf25f42c84d2fcb67e3675469c3b5d14"
metafile = true

[[files]]
file = "mods/mafglib.pw.toml"
hash = "58020b79db83e23e241b662de7ba078e80acd4c36d3825c2a2848f99c4f0e32e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a9593968393bae08257ba9aae887ad60fc49991f676b637006b2bcd89907f09a"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "1aacabeaeae215e2ce6ba51a1c087460152cefa1fe32070fb80fbe1fa1360b05"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/nirvana-library.pw.toml"
hash = "6048c4793611860f18d124f2e52c019a6e90f62c03c453d2bf9fbdaa29ac97f3"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5da18814472be5dc93a21886983646da3a7236413800075ac75229be82d114fa"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "09ba6db54e6f13fafa1e12a9adcd83db9137617d631288579f520ab11b4bfe9a"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "4735b502110228fe33b9a957794689f309e3a7019fff26390a10f750d074ed32"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "d9b38ba42434eb436d036b1c8add839bee003240dc85cc54ec626aac58c59070"
metafile = true

[[files]]
file = "mods/probejs.pw.toml"
hash = "98bbba48eddf402b09107de563d7b4370d1ae70a1a6210054cd13065072a9d97"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "989b2aeb18f4004fb9b7932951de4b38ffa0fc6bf5360ac32ffe9af08391d04d"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "6b91f46291891e725189b0bd54d0db0f66925b1e785bdfa737592dfcf41a79a3"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "a182489f5f19738fd9b93d796d9e660df95fa02273a3f55f70f36314222a40a2"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "c5687771065e4a43266b38018cbdf142b216916dd73aa6532b8282e3d0f06b9c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "9d76c3683cfea5c5976823a000eacc9944db9f097894356d2a029cf36642ffa4"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip.txt"
hash = "606414ef3e197966e1e8cf0ba38e44fe9681ee56d51b749b84cb754e95a84189"

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "531a8d239c952428d9a633ff99cb03461656ada28decbe2e1ef19f60f7fd5726"
metafile = true
