name = "Card Hunters"
author = "lonevox"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a515a8dc506c7fd49bc02dd4fdb239ef42a3af38191563f98e8c1d657c48bae3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
